services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=madal586
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=madal586
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: moh586/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=madal586;Database=auctions
      - IdentityServiceUrl=http://identity-svc
      #- Kestrel__Endpoints__Grpc__Protocols=Http2
      #- Kestrel__Endpoints__Grpc__Url=http://+:7777
      #- Kestrel__Endpoints__WebApi__Protocols=Http1
      #- Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7001:80
    #  - 7777:7777
    depends_on:
      - postgres
      - rabbitmq
    #networks:
    #  custom:
  search-svc:
    image: moh586/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:madal586@mongodb
      - AuctionServiceUrl=http://auction-svc
      #- Kestrel__Endpoints__Grpc__Protocols=Http2
      #- Kestrel__Endpoints__Grpc__Url=http://+:7777
      #- Kestrel__Endpoints__WebApi__Protocols=Http1
      #- Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 7002:80
    #  - 7777:7777
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: moh586/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      #- ClientApp=http://app.carsties.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=madal586;Database=identity
      #- VIRTUAL_HOST=id.carsties.com
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: moh586/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      #- ClientApp=http://app.carsties.com
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=madal586;Database=identity
      #- VIRTUAL_HOST=id.carsties.com
    ports:
      - 6001:80
